version: '3.7'

services:
  db:
    image: ${DB_IMAGE}
    container_name: ${DB_CONTAINER_NAME}
#    When running on ARM64 use MariaDB instead of MySQL
#    image: mariadb:10.4
#    For auto DB backups comment out image and use the build block below
#    build:
#      context: ./config/mysql
#    ports:
#      - "3305:3306"
    restart: always
    env_file: .env
    volumes:
      - invoiceninja5_db:/var/lib/mysql

      # remove comments for next 4 lines if you want auto sql backups
      #- ./docker/mysql/bak:/backups:rw
      #- ./config/mysql/backup-script:/etc/cron.daily/daily:ro
      #- ./config/mysql/backup-script:/etc/cron.weekly/weekly:ro
      #- ./config/mysql/backup-script:/etc/cron.monthly/monthly:ro
    networks:
      - invoiceninja5
#    extra_hosts:
#      - "in5.localhost:192.168.0.124 " #host and ip

  # THIS IS ONLY A VALID CONFIGURATION FOR IN 4. DO NOT USE FOR IN 5.
  # cron:
  #   image: invoiceninja/invoiceninja:alpine-4
  #   volumes:
      # - ./docker/app/public:/var/www/app/public:rw,delegated
      # - ./docker/app/storage:/var/www/app/storage:rw,delegated
      # - ./docker/app/public/logo:/var/www/app/public/logo:rw,delegated
  #   entrypoint: |
  #     /bin/sh -c 'sh -s <<EOF
  #     trap "break;exit" SIGHUP SIGINT SIGTERM
  #     sleep 300s
  #     while /bin/true; do
  #       ./artisan ninja:send-invoices
  #       ./artisan ninja:send-reminders
  #       sleep 1d
  #     done
  #     EOF'
  #   networks:
  #     - invoiceninja
  #
  app:
    image: ${APP_IMAGE}
    container_name: ${APP_CONTAINER_NAME}
    env_file: .env
    restart: always
    volumes:
#      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
    depends_on:
      - db
    networks:
      - invoiceninja5
      - reverseproxy
#    extra_hosts:
#      - "in5.localhost:192.168.0.124 " #host and ip
  server:
    image: nginx
    container_name: ${NGINX_CONTAINER_NAME}
    restart: always
    env_file: .env
    volumes:
      # Vhost configuration
      #- ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:ro
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
#    ports:
#      - "80:80"
      #- "443:443"
    networks:
      - reverseproxy
#    extra_hosts:
#      - "in5.localhost:192.168.0.124 " #host and ip


networks:
  invoiceninja5:
   external: true
  reverseproxy:
   external: true

volumes:
  invoiceninja5_db:
    external: true